#! /bin/bash

srcdir=$(dirname "$0")

arch=x86_64
if ! test "x$1" = "x" ; then
    arch=$1
fi

sysdir="$(pwd)/rootfs"
mkdir -p newlib && cd newlib

${srcdir}/newlib/configure --prefix="/usr" --target="${arch}-ulmeros" && \
    make -j && \
    make DESTDIR="${sysdir}" install && \
    ln -sfn ${arch}-ulmeros/include ${sysdir}/usr/include
    ln -sfn ${arch}-ulmeros/lib ${sysdir}/usr/lib
